#!/bin/bash
pwd
ls 
if  test -f monfichier.txt 
then
	echo "Le fichier existe"
else	
	echo "Le fichier n'existe pas"
fi
echo "test">>monfichier.txt
ls  
if  test -f monfichier.txt
then
        echo "Le fichier existe "
else
        echo "Le fichier n'existe pas"
fi
ls 


